name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-26-intel]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build
        run: zig build

      - name: Test
        run: zig build test --summary all

      - name: Check formatting
        if: runner.os == 'Linux'
        run: zig fmt --check .

      - name: Run example
        if: runner.os == 'Windows'
        run: ./zig-out/bin/example

      - name: Run example (sudo)
        if: runner.os != 'Windows'
        run: sudo ./zig-out/bin/example
